const shipSeed = [
  {
    name: "100i",
    manufacturer: "Origin Jumpworks",
    role: "Starter/Touring",
    size: "Small",
    currentPrice: "45",
  },
  {
    name: "125a",
    manufacturer: "Origin Jumpworks",
    role: "Starter/Light Fighter",
    size: "Small",
    currentPrice: "55",
  },
  {
    name: "135c",
    manufacturer: "Origin Jumpworks",
    role: "Starter/Light Freight",
    size: "Small",
    currentPrice: "60",
  },
  {
    name: "300i",
    manufacturer: "Origin Jumpworks",
    role: "Touring",
    size: "Small",
    currentPrice: "55",
  },
  {
    name: "315p",
    manufacturer: "Origin Jumpworks",
    role: "Pathfinder",
    size: "Small",
    currentPrice: "65",
  },
  {
    name: "325a",
    manufacturer: "Origin Jumpworks",
    role: "Interdiction",
    size: "Small",
    currentPrice: "70",
  },
  {
    name: "350r",
    manufacturer: "Origin Jumpworks",
    role: "Racing",
    size: "Small",
    currentPrice: "125",
  },
  {
    name: "600i",
    manufacturer: "Origin Jumpworks",
    role: "Personal Transport",
    size: "Large",
    currentPrice: "435",
  },
  {
    name: "85X",
    manufacturer: "Origin Jumpworks",
    role: "Touring",
    size: "Snub",
    currentPrice: "50",
  },
  {
    name: "890 Jump",
    manufacturer: "Origin Jumpworks",
    role: "Touring",
    size: "Capital",
    currentPrice: "950",
  },
  {
    name: "A2 Hercules",
    manufacturer: "Crusader Industries",
    role: "Heavy Military Lifting",
    size: "Large",
    currentPrice: "700",
  },
  {
    name: "Ankar",
    manufacturer: "Vanduul Clans",
    role: "Small Bomber",
    size: "Small",
    currentPrice: "",
  },
  {
    name: "Apollo Medivac",
    manufacturer: "Roberts Space Industries",
    role: "Support - Medical",
    size: "Medium",
    currentPrice: "275",
  },
  {
    name: "Apollo Triage",
    manufacturer: "Roberts Space Industries",
    role: "Support - Medical",
    size: "Medium",
    currentPrice: "250",
  },
  {
    name: "Ares Inferno",
    manufacturer: "Crusader Industries",
    role: "Anti-Capital",
    size: "Medium",
    currentPrice: "220",
  },
  {
    name: "Ares Ion",
    manufacturer: "Crusader Industries",
    role: "Anti-Capital",
    size: "Medium",
    currentPrice: "220",
  },
  {
    name: "Arrow",
    manufacturer: "Anvil Aerospace",
    role: "Light Fighter",
    size: "Small",
    currentPrice: "75",
  },
  {
    name: "Aurora CL",
    manufacturer: "Roberts Space Industries",
    role: "Light Freight",
    size: "Small",
    currentPrice: "45",
  },
  {
    name: "Aurora ES",
    manufacturer: "Roberts Space Industries",
    role: "Pathfinder",
    size: "Small",
    currentPrice: "20",
  },
  {
    name: "Aurora LN",
    manufacturer: "Roberts Space Industries",
    role: "Light Fighter",
    size: "Small",
    currentPrice: "35",
  },
  {
    name: "Aurora LX",
    manufacturer: "Roberts Space Industries",
    role: "Pathfinder",
    size: "Small",
    currentPrice: "30",
  },
  {
    name: "Aurora MR",
    manufacturer: "Roberts Space Industries",
    role: "Light Fighter",
    size: "Small",
    currentPrice: "25",
  },
  {
    name: "Avenger Stalker",
    manufacturer: "Aegis Dynamics",
    role: "Interdiction",
    size: "Small",
    currentPrice: "60",
  },
  {
    name: "Avenger Titan",
    manufacturer: "Aegis Dynamics",
    role: "Light Freight",
    size: "Small",
    currentPrice: "50",
  },
  {
    name: "Avenger Titan Renegade",
    manufacturer: "Aegis Dynamics",
    role: "Light Freight",
    size: "Small",
    currentPrice: "75",
  },
  {
    name: "Avenger Trainer",
    manufacturer: "Aegis Dynamics",
    role: "Combat",
    size: "Small",
    currentPrice: "",
  },
  {
    name: "Avenger Warlock",
    manufacturer: "Aegis Dynamics",
    role: "Interdiction",
    size: "Small",
    currentPrice: "85",
  },
  {
    name: "Bengal",
    manufacturer: "Roberts Space Industries",
    role: "Carrier",
    size: "Capital",
    currentPrice: "",
  },
  {
    name: "Blade",
    manufacturer: "Vanduul Clans",
    role: "Light Fighter",
    size: "Small",
    currentPrice: "",
  },
  {
    name: "Blade (replica)",
    manufacturer: "Esperia",
    role: "Light Fighter",
    size: "Small",
    currentPrice: "275",
  },
  {
    name: "Buccaneer",
    manufacturer: "Drake Interplanetary",
    role: "Interdiction",
    size: "Small",
    currentPrice: "110",
  },
  {
    name: "C2 Hercules",
    manufacturer: "Crusader Industries",
    role: "Heavy Lifting",
    size: "Large",
    currentPrice: "360",
  },
  {
    name: "C8 Pisces",
    manufacturer: "Anvil Aerospace",
    role: "Pathfinder",
    size: "Snub",
    currentPrice: "",
  },
  {
    name: "C8X Pisces Expedition",
    manufacturer: "Anvil Aerospace",
    role: "Pathfinder",
    size: "Snub",
    currentPrice: "45",
  },
  {
    name: "Carrack",
    manufacturer: "Anvil Aerospace",
    role: "Expedition",
    size: "Large",
    currentPrice: "600",
  },
  {
    name: "Caterpillar",
    manufacturer: "Drake Interplanetary",
    role: "Transport",
    size: "Large",
    currentPrice: "295",
  },
  {
    name: "Cleaver",
    manufacturer: "Vanduul Clans",
    role: "Boarding",
    size: "Snub",
    currentPrice: "",
  },
  {
    name: "Constellation Andromeda",
    manufacturer: "Roberts Space Industries",
    role: "Medium Freight",
    size: "Large",
    currentPrice: "225",
  },
  {
    name: "Constellation Aquila",
    manufacturer: "Roberts Space Industries",
    role: "Expedition",
    size: "Large",
    currentPrice: "310",
  },
  {
    name: "Constellation Phoenix",
    manufacturer: "Roberts Space Industries",
    role: "Touring",
    size: "Large",
    currentPrice: "350",
  },
  {
    name: "Constellation Taurus",
    manufacturer: "Roberts Space Industries",
    role: "Medium Freight",
    size: "Large",
    currentPrice: "150",
  },
  {
    name: "Corsair",
    manufacturer: "Drake Interplanetary",
    role: "Exploration",
    size: "Large",
    currentPrice: "215",
  },
  {
    name: "Crawler",
    manufacturer: "Vanduul Clans",
    role: "Boarding ship",
    size: "Medium",
    currentPrice: "",
  },
  {
    name: "Crucible",
    manufacturer: "Anvil Aerospace",
    role: "Heavy Repair",
    size: "Large",
    currentPrice: "350",
  },
  {
    name: "Cutlass Black",
    manufacturer: "Drake Interplanetary",
    role: "Medium Fighter / Medium Freight",
    size: "Medium",
    currentPrice: "100",
  },
  {
    name: "Cutlass Blue",
    manufacturer: "Drake Interplanetary",
    role: "Police / Bounty Hunter",
    size: "Medium",
    currentPrice: "150",
  },
  {
    name: "Cutlass Red",
    manufacturer: "Drake Interplanetary",
    role: "Search & Rescue",
    size: "Medium",
    currentPrice: "135",
  },
  {
    name: "Cutter",
    manufacturer: "Aegis Dynamics",
    role: "Drone",
    size: "Small",
    currentPrice: "",
  },
  {
    name: "Cydnus",
    manufacturer: "Greycat Industrial",
    role: "Mining",
    size: "Medium",
    currentPrice: "",
  },
  {
    name: "Defender",
    manufacturer: "Banu Souli",
    role: "Light Fighter",
    size: "Small",
    currentPrice: "220",
  },
  {
    name: "DireHawk",
    manufacturer: "Anvil Aerospace",
    role: "",
    size: "Small",
    currentPrice: "",
  },
  {
    name: "Dragonfly",
    manufacturer: "Drake Interplanetary",
    role: "Racing",
    size: "Snub",
    currentPrice: "40",
  },
  {
    name: "Driller",
    manufacturer: "Vanduul Clans",
    role: "Escort Carrier",
    size: "Capital",
    currentPrice: "",
  },
  {
    name: "Eclipse",
    manufacturer: "Aegis Dynamics",
    role: "Stealth Bomber",
    size: "Medium",
    currentPrice: "300",
  },
  {
    name: "Endeavor",
    manufacturer: "Musashi Industrial and Starflight Concern",
    role: "Heavy Science",
    size: "Capital",
    currentPrice: "350",
  },
  {
    name: "F7A Hornet",
    manufacturer: "Anvil Aerospace",
    role: "Medium Fighter",
    size: "Small",
    currentPrice: "",
  },
  {
    name: "F7A Hornet Mk II",
    manufacturer: "Anvil Aerospace",
    role: "Military Close Support",
    size: "Small",
    currentPrice: "",
  },
  {
    name: "F7A-R Hornet Tracker",
    manufacturer: "Anvil Aerospace",
    role: "Scout",
    size: "Small",
    currentPrice: "",
  },
  {
    name: "F7C Hornet",
    manufacturer: "Anvil Aerospace",
    role: "Medium fighter",
    size: "Small",
    currentPrice: "110",
  },
  {
    name: "F7C Hornet Wildfire",
    manufacturer: "Anvil Aerospace",
    role: "Medium Fighter",
    size: "Small",
    currentPrice: "175",
  },
  {
    name: "F7C-M Super Hornet",
    manufacturer: "Anvil Aerospace",
    role: "Medium Fighter",
    size: "Small",
    currentPrice: "180",
  },
  {
    name: "F7C-M Super Hornet Heartseeker",
    manufacturer: "Anvil Aerospace",
    role: "Medium Fighter",
    size: "Small",
    currentPrice: "",
  },
  {
    name: "F7C-R Hornet Tracker",
    manufacturer: "Anvil Aerospace",
    role: "Pathfinder",
    size: "Small",
    currentPrice: "140",
  },
  {
    name: "F7C-S Hornet Ghost",
    manufacturer: "Anvil Aerospace",
    role: "Stealth Fighter",
    size: "Small",
    currentPrice: "125",
  },
  {
    name: "F8A Lightning",
    manufacturer: "Anvil Aerospace",
    role: "Heavy fighter",
    size: "Small",
    currentPrice: "",
  },
  {
    name: "F8C Lightning",
    manufacturer: "Anvil Aerospace",
    role: "Heavy fighter",
    size: "Small",
    currentPrice: "",
  },
  {
    name: "Freelancer",
    manufacturer: "Musashi Industrial and Starflight Concern",
    role: "Transport",
    size: "Medium",
    currentPrice: "110",
  },
  {
    name: "Freelancer DUR",
    manufacturer: "Musashi Industrial and Starflight Concern",
    role: "Exploration",
    size: "Medium",
    currentPrice: "135",
  },
  {
    name: "Freelancer MAX",
    manufacturer: "Musashi Industrial and Starflight Concern",
    role: "Medium Freight",
    size: "Medium",
    currentPrice: "150",
  },
  {
    name: "Freelancer MIS",
    manufacturer: "Musashi Industrial and Starflight Concern",
    role: "Combat",
    size: "Medium",
    currentPrice: "175",
  },
  {
    name: "Genesis Starhunter",
    manufacturer: "Crusader Industries",
    role: "Patrol Hunter-Killer",
    size: "Large",
    currentPrice: "",
  },
  {
    name: "Genesis Starliner",
    manufacturer: "Crusader Industries",
    role: "Passenger Transport",
    size: "Large",
    currentPrice: "400",
  },
  {
    name: "Genesis Starseeker",
    manufacturer: "Crusader Industries",
    role: "SWACS/C&C platform",
    size: "Large",
    currentPrice: "",
  },
  {
    name: "Gladiator",
    manufacturer: "Anvil Aerospace",
    role: "Light Bomber",
    size: "Small",
    currentPrice: "165",
  },
  {
    name: "Gladius",
    manufacturer: "Aegis Dynamics",
    role: "Light Fighter",
    size: "Small",
    currentPrice: "90",
  },
  {
    name: "Gladius Valiant",
    manufacturer: "Aegis Dynamics",
    role: "Short-range Dogfighter",
    size: "Small",
    currentPrice: "110",
  },
  {
    name: "Glaive",
    manufacturer: "Vanduul Clans",
    role: "Medium Fighter",
    size: "Medium",
    currentPrice: "",
  },
  {
    name: "Glaive (replica)",
    manufacturer: "Esperia",
    role: "Medium Fighter",
    size: "Medium",
    currentPrice: "350",
  },
  {
    name: "Guine",
    manufacturer: "Unknown manufacturer",
    role: "Patrol ship",
    size: "Large",
    currentPrice: "",
  },
  {
    name: "Hammerhead",
    manufacturer: "Aegis Dynamics",
    role: "Heavy Gun Ship",
    size: "Large",
    currentPrice: "725",
  },
  {
    name: "Harvester",
    manufacturer: "Vanduul Clans",
    role: "Scavenging, Mining, Refining ?, Recycling",
    size: "",
    currentPrice: "",
  },
  {
    name: "Harvester Carrier",
    manufacturer: "Vanduul Clans",
    role: "Carrier",
    size: "",
    currentPrice: "",
  },
  {
    name: "Hatchet",
    manufacturer: "Vanduul Clans",
    role: "Medium Cargo",
    size: "Medium",
    currentPrice: "",
  },
  {
    name: "Hawk",
    manufacturer: "Anvil Aerospace",
    role: "Light Fighter",
    size: "Small",
    currentPrice: "100",
  },
  {
    name: "Herald",
    manufacturer: "Drake Interplanetary",
    role: "Medium Data",
    size: "Small",
    currentPrice: "85",
  },
  {
    name: "Hull A",
    manufacturer: "Musashi Industrial and Starflight Concern",
    role: "Cargo",
    size: "Small",
    currentPrice: "60",
  },
  {
    name: "Hull B",
    manufacturer: "Musashi Industrial and Starflight Concern",
    role: "Heavy Freight",
    size: "Medium",
    currentPrice: "90",
  },
  {
    name: "Hull C",
    manufacturer: "Musashi Industrial and Starflight Concern",
    role: "Heavy Freight",
    size: "Large",
    currentPrice: "250",
  },
  {
    name: "Hull D",
    manufacturer: "Musashi Industrial and Starflight Concern",
    role: "Transport",
    size: "Capital",
    currentPrice: "350",
  },
  {
    name: "Hull E",
    manufacturer: "Musashi Industrial and Starflight Concern",
    role: "Transport",
    size: "Capital",
    currentPrice: "650",
  },
  {
    name: "Hunter",
    manufacturer: "Vanduul Clans",
    role: "Corvette",
    size: "Large",
    currentPrice: "",
  },
  {
    name: "Hurricane",
    manufacturer: "Anvil Aerospace",
    role: "Heavy Fighter",
    size: "Small",
    currentPrice: "195",
  },
  {
    name: "Idris-K",
    manufacturer: "Aegis Dynamics",
    role: "Frigate",
    size: "Capital",
    currentPrice: "1800",
  },
  {
    name: "Idris-M",
    manufacturer: "Aegis Dynamics",
    role: "Frigate",
    size: "Capital",
    currentPrice: "1000",
  },
  {
    name: "Idris-P",
    manufacturer: "Aegis Dynamics",
    role: "Frigate",
    size: "Capital",
    currentPrice: "1500",
  },
  {
    name: "Indefatigable",
    manufacturer: "Unknown manufacturer",
    role: "Battleship",
    size: "Capital",
    currentPrice: "",
  },
  {
    name: "Javelin",
    manufacturer: "Aegis Dynamics",
    role: "Destroyer",
    size: "Capital",
    currentPrice: "3000",
  },
  {
    name: "Jupiter (ship)",
    manufacturer: "Crusader Industries",
    role: "Carrier",
    size: "Capital",
    currentPrice: "",
  },
  {
    name: "Khartu-al",
    manufacturer: "Aopoa",
    role: "Light Fighter",
    size: "Small",
    currentPrice: "170",
  },
  {
    name: "Kingship",
    manufacturer: "Vanduul Clans",
    role: "Carrier",
    size: "Capital",
    currentPrice: "",
  },
  {
    name: "Kraken",
    manufacturer: "Drake Interplanetary",
    role: "Support",
    size: "Capital",
    currentPrice: "1650",
  },
  {
    name: "Kraken Privateer",
    manufacturer: "Drake Interplanetary",
    role: "Multi-role, light carrier",
    size: "Capital",
    currentPrice: "2000",
  },
  {
    name: "Lightfire",
    manufacturer: "Vanduul Clans",
    role: "Comms Ship",
    size: "Capital",
    currentPrice: "",
  },
  {
    name: "M2 Hercules",
    manufacturer: "Crusader Industries",
    role: "Heavy Military Lifting",
    size: "Large",
    currentPrice: "480",
  },
  {
    name: "M50",
    manufacturer: "Origin Jumpworks",
    role: "Racing/Interdiction",
    size: "Small",
    currentPrice: "100",
  },
  {
    name: "MPUV Cargo",
    manufacturer: "Argo Astronautics",
    role: "Light Freight",
    size: "Snub",
    currentPrice: "35",
  },
  {
    name: "MPUV Personnel",
    manufacturer: "Argo Astronautics",
    role: "Passenger",
    size: "Snub",
    currentPrice: "40",
  },
  {
    name: "Mantis",
    manufacturer: "Roberts Space Industries",
    role: "Interdiction",
    size: "Small",
    currentPrice: "150",
  },
  {
    name: "Mauler",
    manufacturer: "Vanduul Clans",
    role: "Cruiser",
    size: "Capital",
    currentPrice: "",
  },
  {
    name: "Merchantman",
    manufacturer: "Banu Souli",
    role: "Heavy Freight",
    size: "Large",
    currentPrice: "350",
  },
  {
    name: "Mercury Star Runner",
    manufacturer: "Crusader Industries",
    role: "Blockade Runner",
    size: "Medium",
    currentPrice: "225",
  },
  {
    name: "Mole",
    manufacturer: "Argo Astronautics",
    role: "Mining",
    size: "Medium",
    currentPrice: "315",
  },
  {
    name: "Mustang Alpha",
    manufacturer: "Consolidated Outland",
    role: "Light Freight",
    size: "Small",
    currentPrice: "30",
  },
  {
    name: "Mustang Beta",
    manufacturer: "Consolidated Outland",
    role: "Pathfinder",
    size: "Small",
    currentPrice: "40",
  },
  {
    name: "Mustang Delta",
    manufacturer: "Consolidated Outland",
    role: "Light Fighter",
    size: "Small",
    currentPrice: "65",
  },
  {
    name: "Mustang Gamma",
    manufacturer: "Consolidated Outland",
    role: "Racing",
    size: "Small",
    currentPrice: "55",
  },
  {
    name: "Mustang Omega",
    manufacturer: "Consolidated Outland",
    role: "Competition",
    size: "Small",
    currentPrice: "",
  },
  {
    name: "Nautilus",
    manufacturer: "Aegis Dynamics",
    role: "Minelayer",
    size: "Large",
    currentPrice: "725",
  },
  {
    name: "Nova (ship)",
    manufacturer: "Roberts Space Industries",
    role: "Courier",
    size: "",
    currentPrice: "",
  },
  {
    name: "Nox",
    manufacturer: "Aopoa",
    role: "Space and Ground Racing",
    size: "Snub",
    currentPrice: "45",
  },
  {
    name: "Oracle",
    manufacturer: "Unknown manufacturer",
    role: "Carrier",
    size: "Capital",
    currentPrice: "",
  },
  {
    name: "Orbital Utility Craft",
    manufacturer: "Argo Astronautics",
    role: "Freight",
    size: "",
    currentPrice: "",
  },
  {
    name: "Orion",
    manufacturer: "Roberts Space Industries",
    role: "Mining",
    size: "Capital",
    currentPrice: "575",
  },
  {
    name: "P-52 Merlin",
    manufacturer: "Kruger Intergalactic",
    role: "Snub Fighter",
    size: "Snub",
    currentPrice: "25",
  },
  {
    name: "P-72 Archimedes",
    manufacturer: "Kruger Intergalactic",
    role: "Racing",
    size: "Snub",
    currentPrice: "35",
  },
  {
    name: "Pegasus",
    manufacturer: "Roberts Space Industries",
    role: "Escort Carrier",
    size: "Capital",
    currentPrice: "",
  },
  {
    name: "Pioneer",
    manufacturer: "Consolidated Outland",
    role: "Heavy Construction",
    size: "Capital",
    currentPrice: "850",
  },
  {
    name: "Polaris",
    manufacturer: "Roberts Space Industries",
    role: "Corvette",
    size: "Capital",
    currentPrice: "750",
  },
  {
    name: "Prospector",
    manufacturer: "Musashi Industrial and Starflight Concern",
    role: "Mining",
    size: "Small",
    currentPrice: "155",
  },
  {
    name: "Prowler",
    manufacturer: "Esperia",
    role: "Drop ship",
    size: "Medium",
    currentPrice: "440",
  },
  {
    name: "Qhire Khartu",
    manufacturer: "Aopoa",
    role: "Light Fighter",
    size: "Small",
    currentPrice: "",
  },
  {
    name: "Razor",
    manufacturer: "Musashi Industrial and Starflight Concern",
    role: "Racing",
    size: "Small",
    currentPrice: "145",
  },
  {
    name: "Razor EX",
    manufacturer: "Musashi Industrial and Starflight Concern",
    role: "Stealth",
    size: "Small",
    currentPrice: "155",
  },
  {
    name: "Razor LX",
    manufacturer: "Musashi Industrial and Starflight Concern",
    role: "Racing",
    size: "Small",
    currentPrice: "150",
  },
  {
    name: "Reaper (ship)",
    manufacturer: "Unknown manufacturer",
    role: "",
    size: "Capital",
    currentPrice: "",
  },
  {
    name: "Reclaimer",
    manufacturer: "Aegis Dynamics",
    role: "Heavy Salvage",
    size: "Large",
    currentPrice: "400",
  },
  {
    name: "Redeemer",
    manufacturer: "Aegis Dynamics",
    role: "Gunship",
    size: "Medium",
    currentPrice: "250",
  },
  {
    name: "Reliant Kore",
    manufacturer: "Musashi Industrial and Starflight Concern",
    role: "Light Freight",
    size: "Small",
    currentPrice: "65",
  },
  {
    name: "Reliant Mako",
    manufacturer: "Musashi Industrial and Starflight Concern",
    role: "Reporting",
    size: "Small",
    currentPrice: "95",
  },
  {
    name: "Reliant Sen",
    manufacturer: "Musashi Industrial and Starflight Concern",
    role: "Light Science",
    size: "Small",
    currentPrice: "85",
  },
  {
    name: "Reliant Tana",
    manufacturer: "Musashi Industrial and Starflight Concern",
    role: "Light Fighter",
    size: "Small",
    currentPrice: "75",
  },
  {
    name: "Retaliator",
    manufacturer: "Aegis Dynamics",
    role: "Heavy Bomber",
    size: "Large",
    currentPrice: "275",
  },
  {
    name: "Retribution",
    manufacturer: "UEE Navy",
    role: "Flagship",
    size: "Capital",
    currentPrice: "",
  },
  {
    name: "SRV",
    manufacturer: "Argo Astronautics",
    role: "Tugging",
    size: "Small",
    currentPrice: "150",
  },
  {
    name: "Sabre",
    manufacturer: "Aegis Dynamics",
    role: "Stealth Fighter",
    size: "Small",
    currentPrice: "170",
  },
  {
    name: "Sabre Comet",
    manufacturer: "Aegis Dynamics",
    role: "Combat",
    size: "Small",
    currentPrice: "185",
  },
  {
    name: "Sabre Raven",
    manufacturer: "Aegis Dynamics",
    role: "Combat",
    size: "Small",
    currentPrice: "",
  },
  {
    name: "San'tok.yāi",
    manufacturer: "Aopoa",
    role: "Medium Fighter",
    size: "Small",
    currentPrice: "220",
  },
  {
    name: "Scythe",
    manufacturer: "Vanduul Clans",
    role: "Medium Fighter",
    size: "Small",
    currentPrice: "300",
  },
  {
    name: "Scythe (replica)",
    manufacturer: "Esperia",
    role: "Medium Fighter",
    size: "Small",
    currentPrice: "",
  },
  {
    name: "ShadowHawk",
    manufacturer: "Anvil Aerospace",
    role: "",
    size: "Small",
    currentPrice: "",
  },
  {
    name: "Starfarer",
    manufacturer: "Musashi Industrial and Starflight Concern",
    role: "Refueling",
    size: "Large",
    currentPrice: "300",
  },
  {
    name: "Starfarer Gemini",
    manufacturer: "Musashi Industrial and Starflight Concern",
    role: "Military Refueling",
    size: "Large",
    currentPrice: "340",
  },
  {
    name: "Stinger",
    manufacturer: "Vanduul Clans",
    role: "Heavy Fighter",
    size: "Medium",
    currentPrice: "",
  },
  {
    name: "T8A Gladiator",
    manufacturer: "Anvil Aerospace",
    role: "Light Bomber",
    size: "Small",
    currentPrice: "",
  },
  {
    name: "Terrapin",
    manufacturer: "Anvil Aerospace",
    role: "Scout",
    size: "Small",
    currentPrice: "220",
  },
  {
    name: "Tomahawk",
    manufacturer: "Vanduul Clans",
    role: "Heavy Cargo",
    size: "Large",
    currentPrice: "",
  },
  {
    name: "Type-IV",
    manufacturer: "Unknown manufacturer",
    role: "Cargo",
    size: "",
    currentPrice: "",
  },
  {
    name: "Valkyrie",
    manufacturer: "Anvil Aerospace",
    role: "Heavy Dropship",
    size: "Medium",
    currentPrice: "375",
  },
  {
    name: "Vanguard Harbinger",
    manufacturer: "Aegis Dynamics",
    role: "Bomber",
    size: "Medium",
    currentPrice: "290",
  },
  {
    name: "Vanguard Hoplite",
    manufacturer: "Aegis Dynamics",
    role: "Dropship",
    size: "Medium",
    currentPrice: "235",
  },
  {
    name: "Vanguard Sentinel",
    manufacturer: "Aegis Dynamics",
    role: "Electronic Warfare",
    size: "Medium",
    currentPrice: "275",
  },
  {
    name: "Vanguard Warden",
    manufacturer: "Aegis Dynamics",
    role: "Heavy Fighter",
    size: "Medium",
    currentPrice: "260",
  },
  {
    name: "Void",
    manufacturer: "Vanduul Clans",
    role: "Heavy Bomber",
    size: "Large",
    currentPrice: "",
  },
  {
    name: "Volper",
    manufacturer: "Xi’an",
    role: "Light Bomber",
    size: "",
    currentPrice: "",
  },
  {
    name: "Vulcan",
    manufacturer: "Aegis Dynamics",
    role: "Medium Repair / Medium Refuel",
    size: "Medium",
    currentPrice: "200",
  },
  {
    name: "Vulture",
    manufacturer: "Drake Interplanetary",
    role: "Salvage",
    size: "Small",
    currentPrice: "140",
  },
  {
    name: "X1",
    manufacturer: "Origin Jumpworks",
    role: "Ultra-light Space and Ground",
    size: "Snub",
    currentPrice: "40",
  },
  {
    name: "X1 Force",
    manufacturer: "Origin Jumpworks",
    role: "Ultra-light Space and Ground",
    size: "Snub",
    currentPrice: "50",
  },
  {
    name: "X1 Velocity",
    manufacturer: "Origin Jumpworks",
    role: "Space and Ground Racing",
    size: "Snub",
    currentPrice: "45",
  },
  {
    name: "Zeus",
    manufacturer: "Roberts Space Industries",
    role: "Exploration",
    size: "",
    currentPrice: "",
  },
];

export default shipSeed;
